### ISSUE TITLE
Update GUI screenshots in two GUI chapters

### ISSUE THREAD

**Issue by bwittman** [start-concurrent/start-concurrent.github.io#115]
The two GUI chapters use old (Windows 7?) images.

They should be updated to Windows 10, ideally at a higher resolution.  Windows 10 is more minimalist than Windows 7 and is, of course, current.

A case could be made for macOS instead.

**Comment by jtkorb** [comment]
I've been thinking about automating the screenshot creation process.  It seems that it might be possible to use JUnit to both create test cases for the programs in general, as well as creating screenshots for both testing and use in the book.  Have you considered this?

**Comment by jtkorb** [comment]
Hmm...  Some screenshots require additional work in two ways: Figure 7.1 (temperature conversion) is (1) a composite of two screenshots and (2) both of which are of programs that don't appear to be in the repository.

**Comment by jtkorb** [comment]
And bat.png from Figure 7.6 is missing.

**Comment by bwittman** [comment]
Pictures would be hard to automate fully.  I recall rescaling a few, but that memory might be wrong.  Also, I occasionally typed a message or interacted in some other way with the widgets before taking the shot.  Finally, in Windows 7, I put all the images on a white background to standardize their partially transparent borders.

I have no doubt that it would be _possible_ to automate the process, but I suspect it would take about 50 times the effort of doing it manually (which really just takes an afternoon or two).  Since I doubt we'll redo it 50 times, I have my doubts about the value of full automation.

There's a part of me that wishes that images appropriate to one's OS could be provided.  Some JavaScript magic could try to detect the browser OS, but a) the browser can always lie, b) injecting the JavaScript into the HTML output might be challenging, and c) reading the book on my iPhone might prompt the system to guess macOS images when I'm really using my phone to help me code on Windows.

**Comment by bwittman** [comment]
#139 closes this.  GUI chapters 7 and 15 have been updated for a while.  The addition of `JFileChooser` to Chapter 20 is the last screenshot update needed for now.
