### ISSUE TITLE
Convert program text references to AsciiDoc callouts

### ISSUE THREAD

**Issue by jtkorb** [start-concurrent/start-concurrent.github.io#23]
Called out lines in program text need to be redone using the AsciiDoc callout feature.

**Comment by bwittman** [comment]
Done by abe9366.

This was not a 1-to-1 mapping, since callouts *must* be described immediately after the program.  Overall, I like the way it forces consistency in describing programs.  No doubt this mindset should be more fully realized in future content revisions.
