### ISSUE TITLE
Use Asciidoctor example and warning syntax for Examples and Pitfalls

### ISSUE THREAD

**Issue by bwittman** [start-concurrent/start-concurrent.github.io#38]
Asciidoctor provides syntax both for examples and warning messages.

An example is formatted like so:

````
.Example Title
====
Example text.
====
````

A warning (useful for Pitfalls) is formatted like so:
````
.Pitfall Title
[WARNING]
====
Pitfall text.
====
````

**Comment by jtkorb** [comment]
I can fix the conversion macros to generate these, if you haven’t started converting them by hand yet.

**Comment by bwittman** [comment]
I only did Chapter 5, none of the others.
