### ISSUE TITLE
Fix cross reference warnings shown by asciidoctor -v 

### ISSUE THREAD

**Issue by jtkorb** [start-concurrent/start-concurrent.github.io#57]
There were 443 warnings when this issue was created.  Some of these are references to program line numbers, which will require some rewriting to fix.  Some are due to a bug/glitch in Asciidoctor concerning labels on titles (captions), for which I have [submitted a question](http://discuss.asciidoctor.org/Paragraph-label-breaks-cross-reference-label-in-paragraph-title-tp6414.html) to the bboards.  Many are for exercises, which have not been properly handled yet.

**Comment by bwittman** [comment]
Fixed by abe9366.

However, using -v still shows problems for exercises, even though the links are good.
