### ISSUE TITLE
Error in conversion from float to decimal

### ISSUE THREAD

**Issue by ssavvides** [start-concurrent/start-concurrent.github.io#80]
I believe in example 19, point 6, conversion is off by one. And the associated figure 5c needs to be adjusted.

**Comment by jtkorb** [comment]
You are correct--thanks for submitting the issue!  Also, congratulations on being our first non-author issue submitter!  :-)

I am pushing a revision to the text and have added a note to the figure.  The figure should be fixed in the next day or two.

**Comment by ssavvides** [comment]
Happy to help Tim.

**Comment by jtkorb** [comment]
The figure was fixed in commit eea8804dd941c7b0eb95e07aecf93d1d55ffd2c3.
